# Generated by Django 3.2.25 on 2026-03-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamajCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='Link to Social Media / Community Page (e.g., Telegram, WhatsApp)')),
                ('icon_class', models.CharField(default='fas fa-users', help_text='FontAwesome icon class (e.g., fab fa-telegram)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
